export const keysInOrder: string[] = [
  'birthDate',
  'twentyFourHours',
  'twentyFourRegrets',
  'oneWeek',
  'oneWeekRegrets',
  'oneMonth',
  'oneMonthRegrets',
  'oneYear',
  'oneYearRegretss',
  'fiveYears',
  'twentyYears',
  'fiftyYears',
  'maxAge'
]

export const timeSpansObj: { [key: string]: string | number } = {
  'birthDate': 'Your Birth Day is ',
  'twentyFourHours': '24 Hours to Live ',
  'twentyFourHoursDays': 1,
  'twentyFourHoursRegrets': 'What regrets would I have? ',
  'oneWeek': '1 Week to Live ',
  'oneWeekDays': 7,
  'oneWeekRegrets': 'What regrets would I have? ',
  'oneMonth': '1 Month to Live ',
  'oneMonthDays': 30,
  'oneMonthRegrets': 'What regrets would I have? ',
  'oneYear': '1 Year to Live ',
  'oneYearDays': 365,
  'oneYearRegrets': 'What regrets would I have? ',
  'fiveYears': '5 Years to Live ',
  'fiveYearsDays': 1826,
  'twentyYears': '20 Years to Live',
  'twentyYearsDays': 7305,
  'fiftyYears': '50 Years to Live ',
  'fiftyYearsDays': 18262,
}


export const TimeSpanPlaceHolderTextObj: { [key: string]: string } = {
  'birthDate': 'Enter Your Birthday',
  'birthDateTitle': 'Birthday',
  'twentyFourHours': 'How would I spend my time if I only had 24 hours to live?',
  'twentyFourHoursRegrets': 'What would I regret if I only had 24 hours to live?',
  'twentyFourHoursTitle': 'Only 24 Hours to Live?',
  'oneWeek': 'How would I spend my time if I only had one week to live?',
  'oneWeekTitle': 'Only One Week to Live?',
  'oneWeekRegrets': 'What would I regret if I only had one week to live?',
  'oneMonth': 'How would I spend my time if I only had one month to live?',
  'oneMonthTitle': 'Only One Month to Live?',
  'oneMonthRegrets': 'What would I regret if I only had one month to live?',
  'oneYear': 'How would I spend my time if I only had one year to live?',
  'oneYearTitle': 'Only One Year to Live?',
  'oneYearRegrets': 'What would I regret if I only had one year to live?',
  'fiveYears': 'How would I spend my time if I only had five years to live?',
  'fiveYearsTitle': 'Only Five Years to Live?',
  'twentyYears': 'How would I spend my time if I only had twenty years to live?',
  'twentyYearsTitle': 'Twenty Years to Live?',
  'fiftyYears': 'How would I spend my time if I only had fifty years to live?',
  'fiftyYearsTitle': 'Fifty Years to Live?',
  'maxAge': 'How old do you expect to live to be?',
  'maxAgeTitle': 'Maximum Age'
}